---
- name: Sample Loops
  hosts: all
  tasks:
    - name: Printing names
      debug:
        msg: "This is {{ item }}"
      with_items:  #you may better use loop here
        - apple
        - bat
        - cat
